- repo: git://github.com/pre-commit/pre-commit-hooks
  sha: 8e0d7bab601ce6a8775ea98082938e60fc80eb7f
  hooks:
    - id: check-added-large-files
    - id: check-symlinks
    - id: check-case-conflict
    - id: check-merge-conflict
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
- repo: git://github.com/detailyang/pre-commit-shell
  sha: 1fdffa0434cde2b87f19ad258201d3e81481af5f
  hooks:
    - id: shell-lint
  args:
    - --exclude=SC1091
